version: '3.9'

services:
  web-ipv4:
    image: busybox
    command: sleep 3600
    networks:
      - app-network
    ports:
      - "0.0.0.0:8000:8000"

  web-ipv6:
    image: busybox
    command: sleep 3600
    networks:
      - app-network
    ports:
      - "[::]:8000:8000"

networks:
  app-network:
    driver: bridge