version: "3.9"

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8081:80"
    networks:
      - mynetwork1

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    networks:
      - mynetwork1

  busybox:
    image: alpine
    container_name: dig
    command: sh -c "sleep infinity"
    networks:
      - mynetwork1
      - mynetwork2

networks:
  mynetwork1:
    driver: bridge

  mynetwork2:
    driver: bridge