services:
  web:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  web-1:
    image: python:3.12-slim
    working_dir: /app2
    volumes:
      - ./app2:/app2
    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge